// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zarijfhqbqelntvkngbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphcmlqZmhxYnFlbG50dmtuZ2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTY5MzMsImV4cCI6MjA2MTI3MjkzM30.0eGA9CDs_u90yMQ--whajoWZM_kcQnlVF5RYMfX0xCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);